### ISSUE TITLE
Impossible to go to step 2 after changing appliance version

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudlaunch-ui#20]
### Steps to reproduce
1. Navigate to https://beta.launch.usegalaxy.org/catalog/appliance/galaxy-cloud
1. Enter valid AWS access key ID and secret key
1. Leave default values in the other two fields
1. Click "Test and Use These Credentials" button
1. Choose a different appliance version from the dropdown (e.g., 16.10)

### Observed results
"NEXT" button is disabled.

### Expected results
"NEXT" button is enabled.

**Comment by nuwang** [comment]
Thanks for reporting this. It seems to occur when there are no previously saved credentials in the dropdown list. Will report back on a fix.

**Comment by nuwang** [comment]
@hackdna This should be fixed now since: https://github.com/galaxyproject/cloudlaunch-ui/commit/b3e0916deb6870612e5f322aaefcb9b2e68214c5
I'll close this for now but please reopen if you run into anymore issues with this.

**Comment by afgane** [comment]
This still doesn't seem quite right. If I have stored creds but choose to use temporary ones and go through that process and after the test choose a different appliance version, the credentials portion of the form refreshes and selects a stored cred, wiping out the temp ones I supplied earlier. Perhaps  we can just disable the version and cloud dropdowns after clicking the `Test and use these creds` button?

**Comment by nuwang** [comment]
The current default behaviour is to reset existing values and highlight the default set of credentials for that version whenever the cloud or version changes. This has its advantages (from a programmer's perspective) because it provides consistent behaviour and we don't need to have special handling for when "test and use creds" is pressed, but is probably not great from a user perspective, because you lose your current temp creds. I think we should file a new issue for this as a future enhancement.

**Comment by hackdna** [comment]
Thanks for looking into this. From my perspective, it'd be great to not even have the "Test and use these creds" button. If a check is necessary it should happen transparently when clicking "Next" or "Save to profile".
